[package]
name = 'word-hold-on'
version = '1.0.0'
authors = []

[addresses]
overmind = "0x1337"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'aptos-cli-v2.0.2'
subdir = 'aptos-move/framework/aptos-framework'
